import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import NextTopLoader from "nextjs-toploader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Ayush's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader showSpinner={false} color="gray"/>
        <div className="bg-slate-200 p-5  ">
      <nav className="flex items-center justify-center space-x-7">
        <Link href={"/"} className="font-semibold hover:text-gray-400 transition-all duration-500">
          About
        </Link>
        <Link href={"/projects"} className="font-semibold  hover:text-gray-400 transition-all duration-500">
          Projects
        </Link>
        <Link href={"/resume"} className="font-semibold  hover:text-gray-400 transition-all duration-500">
          Resume
        </Link>
      </nav>
    </div>
        {children}
      </body>
    </html>
  );
}
